### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by TheSnowfield** [cvolo4yzhka/ZTE_Blade_A476_Kernel#1]
> nyanrabbit@vm:~/bin/los/kernel/ZTE/Blade_A476$ sh compile_kernel.sh
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_kpd.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_kpd.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_eint.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_eint.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_gpio_boot.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_gpio_boot.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_gpio_usage.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_gpio_usage.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_adc.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_adc.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/pmic_drv.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/pmic_drv.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/pmic_drv.c <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/pmic_drv.c dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_eint_md1.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_eint_md1.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_eint.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_eint.dtsi dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_power.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_power.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_clk_buf.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_clk_buf.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_i2c.h <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/inc/cust_i2c.h dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_adc.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_adc.dtsi dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_i2c.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_i2c.dtsi dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_md1_eint.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_md1_eint.dtsi dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_kpd.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_kpd.dtsi dependency dropped.
make[1]: Circular /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_clk_buf.dtsi <- /home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/mach/mt6735/aeon6735m_65u_n_l1/dct/dct/cust_clk_buf.dtsi dependency dropped.
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
 configuration written to .config
  HOSTLD  scripts/mod/modpost
make[2]: Nothing to be done for 'dtbs'.
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
"CONFIG_TRUSTONIC_TEE_SUPPORT = "
/home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/fmradio/Makefile:14: feature_option="MT6625_FM"
/home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/fmradio/Makefile:110: MT6627_FM
/home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/fmradio/Makefile:135: core/fm_module.o core/fm_main.o core/fm_config.o core/fm_rds_parser.o core/fm_patch.o core/fm_utils.o core/fm_link.o core/fm_eint.o mt6627/pub/mt6627_fm_lib.o mt6627/pub/mt6627_fm_rds.o mt6627/pub/mt6627_fm_cmd.o mt6627/pub/mt6627_fm_config.o
mali MTK evironment
imgsensor drv by platform t4ka3_mipi_raw t4ka3_mipi_raw_ofilm ov5670_mipi_raw t4ka3_mipi_raw_sub t4ka3_mipi_raw_cos
/home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/ssw/Makefile:5: "SSW_DIR=/home/nyanrabbit/bin/los/kernel/ZTE/Blade_A476/drivers/misc/mediatek/ssw/ssw_single_v2ssw_exist=y"
  LINK    vmlinux
  LD      vmlinux.o
scripts/link-vmlinux.sh: line 44: ~/bin/los/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-ld: No such file or directory
Makefile:797: recipe for target 'vmlinux' failed
make[1]: *** [vmlinux] Error 1
Makefile:498: recipe for target 'Image.gz-dtb' failed
make: *** [Image.gz-dtb] Error 2

Compiling error, vmlinux.o not exists? 
and how to solve this issue? thanks, waiting for your help

**Comment by TheSnowfield** [comment]
The problem seems to be caused by not finding cc and ld, changed them to absolute path in script/link-vmlinux.sh then problem disappears....

**Comment by cvolo4yzhka** [comment]
compile.sh is wrong, i update it

**Comment by TheSnowfield** [comment]
thank you =3

**Comment by bgman111111** [comment]
sopmeone help me: https://github.com/bgman111111/kernel-mediatek/tree/kernel-4.4
